[project]
name = "restaurant-table-reservations"
version = "0.1.0"
description = ""
authors = [
    {name = "Alexander",email = "you@example.com"}
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[all] (>=0.141.1,<0.142.0)",
    "sqlalchemy (>=2.0.52,<3.0.0)",
    "pydantic (>=2.13.5,<3.0.0)",
    "aiosqlite (>=0.22.1,<0.23.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ruff (>=0.16.5,<0.17.0)"
]


[tool.ruff]
line-length = 88
target-version = "py314"

exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "alembic/versions",
]

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "SIM", # simplify
]

ignore = [
    "B008", # Depends(), Query() и т.д. в FastAPI
]

[tool.ruff.lint.per-file-ignores]
"alembic/env.py" = ["F401"]
"tests/*" = ["S101"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"